Align nullability of BO Vertrag and COM Vertragsteil with BO4E.NET
Hochfrequenz/go-bo4e pull request #297
Opened 2024-05-07 04:41 UTC by hf-kklein

as in BO4E.net v0.4.2
https://github.com/Hochfrequenz/BO4E-dotnet/releases/tag/0.4.2

https://github.com/Hochfrequenz/BO4E-dotnet/blob/c7c9525849cb8c29c5f1d57c53e3435cd281ba43/BO4E/COM/Vertragsteil.cs#L19
https://github.com/Hochfrequenz/BO4E-dotnet/blob/c7c9525849cb8c29c5f1d57c53e3435cd281ba43/BO4E/BO/Vertrag.cs

2024-05-07 04:43 UTC, hf-kklein commented
obsoletes #144

2024-05-27 14:24 UTC, GodsBoss requested changes
I'd prefer not to leave outcommented code, the rest looks fine to me.

2024-05-27 14:24 UTC, GodsBoss commented on bo/businessobject.go
> +		// bo.(*Vertrag).Vertragspartner1.BoTyp = botyp.GESCHAEFTSPARTNER
```suggestion
```

2024-05-27 14:24 UTC, GodsBoss commented on bo/businessobject.go
> +		// bo.(*Vertrag).Vertragspartner2.BoTyp = botyp.GESCHAEFTSPARTNER
```suggestion
```

2024-05-28 05:13 UTC, GodsBoss approved these changes

2024-05-28 06:05 UTC, merged