Implement BO Marktlokation
Hochfrequenz/go-bo4e pull request #38
Opened 2021-11-05 16:06 UTC by hf-aschloegl

2021-11-08 06:12 UTC, hf-kklein requested changes
Sieht schon ganz gut aus :) Danke schön. Nur ein paar Docstring-Sachen sind mir aufgefallen. Beim requried_without_all wäre es spannend zu wissen, wo letztlich noch das Problem liegt, denn offiziell ist dieser Bug mittlerweile gelöst.

2021-11-08 06:12 UTC, hf-kklein commented on bo/marktlokation_test.go
> +	then.AssertThat(s.T(), strings.Contains(string(serializedMalo), "STROM"), is.True())
ich würde die `string(serializedMalo)`-Sache einmal vor den assertions machen und dann mit dem ergebnis arbeiten.

2021-11-08 06:12 UTC, hf-kklein commented on com/messlokationszuordnung.go
> +	GueltigBis      time.Time                                     `json:"gueltigbis"`                                                    // Zeitpunkt, bis zu dem die Messlokation zur Marktlokation gehör
hier bitte auch das format der docstrings so anpassen, dass sie als ersten des Namen des Feldes enthalten, das sie beschreiben.

2021-11-08 06:12 UTC, hf-kklein commented on com/messlokationszuordnung.go
> +	GueltigBis      time.Time                                     `json:"gueltigbis"`                                                    // Zeitpunkt, bis zu dem die Messlokation zur Marktlokation gehör
hier könntest du gt_field verwenden. Es macht fachlcih keinen Sinn, dass Bis früher wäre als Seit.
```suggestion
	GueltigSeit     time.Time                                     `json:"gueltigSeit"validate:"ltefield=GueltigBis`                                                   // Zeitpunkt, ab dem die Messlokation zur Marktlokation gehört
	GueltigBis      time.Time                                     `json:"gueltigbis" validate:"gtefield=GueltigSeit"`                                                    // Zeitpunkt, bis zu dem die Messlokation zur Marktlokation gehört
```

2021-11-08 06:12 UTC, hf-kklein commented on com/messlokationszuordnung.go
> +	GueltigBis      time.Time                                     `json:"gueltigbis"`                                                    // Zeitpunkt, bis zu dem die Messlokation zur Marktlokation gehör
```suggestion
	GueltigSeit     time.Time                                     `json:"gueltigSeit"`                                                   // GueltigSeit ist der inklusive Zeitpunkt, ab dem die Messlokation zur Marktlokation gehört
	GueltigBis      time.Time                                     `json:"gueltigbis"`                                                    // GueltigBis ist der exklusive Zeitpunkt, bis zu dem die Messlokation zur Marktlokation gehört
```
unser lieblingsthema

2021-11-08 06:25 UTC, hf-kklein commented
Ich habe hier mal ein MWE vorbereitet: https://play.golang.org/p/XrjP-iCYufm <-- vllt kannst du das noch aussagekräfitger machen und einen Bug beim validator package eröffnen?

2021-11-10 09:07 UTC, hf-aschloegl commented on bo/marktlokation.go
> +	Bilanzierungsmethode bilanzierungsmethode.Bilanzierungsmethode `json:"bilanzierungsmethode" validate:"required"`                                         // Accounting method
a40bd5a83327777a1589df2816f50de59a8c1494

2021-11-10 09:08 UTC, hf-aschloegl commented on com/messlokationszuordnung.go
> +	GueltigBis      time.Time                                     `json:"gueltigbis"`                                                    // Zeitpunkt, bis zu dem die Messlokation zur Marktlokation gehör
a40bd5a83327777a1589df2816f50de59a8c1494

2021-11-10 09:08 UTC, hf-aschloegl commented on com/messlokationszuordnung.go
> +	GueltigBis      time.Time                                     `json:"gueltigbis"`                                                    // Zeitpunkt, bis zu dem die Messlokation zur Marktlokation gehör
a40bd5a83327777a1589df2816f50de59a8c1494

2021-11-10 10:29 UTC, hf-aschloegl commented on bo/marktlokation.go
> +	Grundversorgercodenr string                                    `json:"grundversorgercodenr,omitempty"`                                                   // Code number of the "Grundversorger" respon
Woher wissen wir das?

2021-11-10 10:29 UTC, hf-aschloegl commented on bo/marktlokation.go
> +	Unterbrechbar        bool                                      `json:"unterbrechbar,omitempty"`                                                          // Identification whether the supply is inter
Ah, gut zu wissen
29df554b255528dd4c756d19e81ebce59e2a3712

2021-11-10 10:29 UTC, hf-aschloegl commented on bo/marktlokation.go
> +	Netzbetreibercodenr  string                                    `json:"netzbetreibercodenr,omitempty" validate:"omitempty,numeric"`                       // Code number of the "Netzbetreiber"
29df554b255528dd4c756d19e81ebce59e2a3712

2021-11-10 10:29 UTC, hf-aschloegl commented on bo/marktlokation.go
> +	Grundversorgercodenr string                                    `json:"grundversorgercodenr,omitempty"`                                                   // Code number of the "Grundversorger" respon
29df554b255528dd4c756d19e81ebce59e2a3712

2021-11-10 10:33 UTC, hf-aschloegl commented on bo/marktlokation.go
> +	Endkunde             Geschaeftspartner                         `json:"endkunde,omitempty" validate:"-"`                                                  // Link to the Geschaeftspartner who owns thi
43a32c9a8cd39df11aa086228fd4450bd25954e2

2021-11-10 10:37 UTC, hf-aschloegl commented on bo/marktlokation.go
> +	Geoadresse                *com.Geokoordinaten          `json:"geoadresse" validate:"required_without_all=Lokationsadresse KatasterInformation"` // Gps coordinates
74dbfceac705869b139df00d903c7343b30b2fbe

2021-11-10 10:37 UTC, hf-aschloegl commented on bo/marktlokation.go
> +func MaloIdFieldLevelValidation(fl validator.FieldLevel) bool {
c05a609d62d3c88eee2177c195721800ece5bff7

2021-11-10 10:41 UTC, hf-aschloegl commented on bo/marktlokation.go
> +	matched, err := regexp.MatchString("[1-9][\\d]{10}$", maloId)
efded9dbf252d0036c43ad288ba9415bcc765ee8

2021-11-10 10:43 UTC, hf-aschloegl commented on bo/marktlokation.go
> +}
Genau, das `required_without_all` ermöglicht, dass es required wird, wenn die anderen nicht da sind, aber es verhindert nicht, dass mehr als eines angegeben wird.

2021-11-10 10:43 UTC, hf-kklein commented on bo/marktlokation.go
> +}
passt für mich, ich habe es ejtzt verstanden.

2021-11-10 10:50 UTC, hf-aschloegl commented on bo/marktlokation_test.go
> +	then.AssertThat(s.T(), strings.Contains(string(serializedMalo), "STROM"), is.True())
ad53ec05fe52e931f192412a3dd06569bfd838d2

2021-11-10 10:50 UTC, hf-kklein approved these changes

2021-11-10 10:50 UTC, hf-aschloegl commented on com/messlokationszuordnung.go
> +	GueltigBis      time.Time                                     `json:"gueltigbis"`                                                    // Zeitpunkt, bis zu dem die Messlokation zur Marktlokation gehör
3c88c076ba4315de93822b03569ad4e00de2ee0c

2021-11-10 10:52 UTC, hf-kklein commented on README.md
> +Whnn adding Enums there are two packages ([stringer](https://pkg.go.dev/golang.org/x/tools/cmd/stringer), [jsonenums](https://github.com/campoy/jsonenums)) needed to go-generate additional files, whi
das is tnoch offen. der typ kam aus meiner suggestion
```suggestion
When adding Enums there are two packages ([stringer](https://pkg.go.dev/golang.org/x/tools/cmd/stringer), [jsonenums](https://github.com/campoy/jsonenums)) needed to go-generate additional files, which contain an implementation of the `fmt.Stringer` and `json.Marshaler` interface for the respective enum.
```

2021-11-10 11:01 UTC, merged